### ISSUE TITLE
Pimpinela

### ISSUE THREAD

**Issue by ZoeDominguez** [pdepjm/2023-tp0-presentacion-CeciC24#2]
Pura curiosidad, ¿cuál es tu canción favorita de los pimpinela?

**Comment by CeciC24** [comment]
Uff que difícil esa pregunta jaja, depende de mi estado de ánimo porque me gustan (casi) todas y mínimo hay una canción de ellos para cada situación 😅, pero creo que podría resumirse en:

- "Estamos todos locos", "Estoy cansada" y "Esa chica y yo" me ponen de buen humor

- "Bastardo", "Una estúpida más" y "Esto no es amor" son de esas canciones para cantar a todo pulmón

- La letra de "El cuento de Superman" me da risa pero me gusta 🤷🏻‍♀️

**Comment by ZoeDominguez** [comment]
Concuerdo que "Una estúpida más" es para cantar a todo pulmón, al igual que "Yo, dueña de la noche", esa canción sirve un montón para mis momentos más esquizo

**Comment by CeciC24** [comment]
"Yo, dueña de la noche" te deja en un mar de lágrimas o te manda al Moyano, no hay punto medio 🤪
